# ls
alias ll='ls -lahG'

# git
alias ga='git add'
alias gac='git add . && git commit'
alias gb='git branch'
alias gbd='git branch -D'
alias gc='git commit'
alias gca='git commit --amend'
alias gch='git checkout'
alias gcl='git clean -df'
alias gd='git diff'
alias gf='git fetch'
alias gfu='git config core.hooksPath /dev/null'
alias gg='git grep'
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gp='git pull --rebase'
alias gpf='git push -f'
alias gpp='git pull --rebase && git push'
alias gpu='git push -u origin `git rev-parse --abbrev-ref HEAD`'
alias gra='git rebase --abort'
alias grc='git rebase --continue'
alias gri='git rebase -i'
alias gri5='git rebase -i HEAD~5'
alias gri10='git rebase -i HEAD~10'
alias grh='git reset --hard'
alias gs='git status'
alias gsh='git show'
alias gsp='git stash pop'
alias gst='git stash'
alias guh='main_ref=$(git symbolic-ref refs/remotes/origin/HEAD); main_branch=${main_ref#refs/remotes/origin/}; git push . origin/${main_branch}:${main_branch}'
alias gur='guh && git rebase ${main_branch}'

# editing
alias e='edit'
alias edit='code -w'

# npm/yarn
alias run='yarn run'
alias yb='yarn run build'
alias yd='yarn run dev'
alias yi='yarn install; git config core.hooksPath /dev/null'
alias yj='yarn run jest'
alias ys='yarn start'
alias yt='yarn run test'
